parameters:
    news: CoreBundle\Entity\News
    photo: CoreBundle\Entity\Photo
    video: CoreBundle\Entity\Video
    comment: CoreBundle\Entity\Comment
    transport: CoreBundle\Entity\Transport

services:
    photo.handler:
        class: CoreBundle\Handler\PhotoHandler
        arguments: [@service_container, %photo%]

    video.handler:
        class: CoreBundle\Handler\VideoHandler
        arguments: [@service_container, %video%]

    news.handler:
        class: CoreBundle\Handler\NewsHandler
        arguments: [@service_container, %news%]

    comment.handler:
        class: CoreBundle\Handler\CommentHandler
        arguments: [@service_container, %comment%]

    transport.handler:
        class: CoreBundle\Handler\TransportHandler
        arguments: [@service_container, %transport%]


    admin.video:
        class: CoreBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-video-camera"></i>', group: "Галерея", label: "Видео" }
        arguments:
            - ~
            - %video%
            - 'SonataAdminBundle:CRUD'

    admin.photo:
        class: CoreBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-picture-o"></i>', group: "Галерея", label: "Фото" }
        arguments:
            - ~
            - %photo%
            - 'SonataAdminBundle:CRUD'

    admin.news:
        class: CoreBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-newspaper-o"></i>', group: "Новости", label: "Новости" }
        arguments:
            - ~
            - %news%
            - 'SonataAdminBundle:CRUD'


    admin.comment:
        class: CoreBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-comment-o"></i>', group: "Новости", label: "Коментарии" }
        arguments:
            - ~
            - %comment%
            - 'SonataAdminBundle:CRUD'

    admin.transport:
        class: CoreBundle\Admin\TransportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-folder-o"></i>', group: "Страницы", label: "Транспорт" }
        arguments:
            - ~
            - %transport%
            - 'SonataAdminBundle:CRUD'

