dolly_profile_page:
    path: /
    defaults: { _controller: AppDollyBundle:Dolly:myProfile }

dolly_profile_order_history:
    path: /order_history
    defaults: { _controller: AppDollyBundle:Dolly:myOrders }

dolly_profile_bonus_history:
    path: /bonushistorikk
    defaults: { _controller: AppDollyBundle:Dolly:myBonusHistory }

dolly_profile_complaints:
    path: /tilbakemelding
    defaults: { _controller: AppDollyBundle:Dolly:complaints }

dolly_profile_save_complaints:
    path: /save_complaints
    defaults: { _controller: AppDollyBundle:Dolly:addComplaints }