dolly_homepage:
    path:     /
    defaults: { _controller: AppDollyBundle:Dolly:index }

dolly_shop:
    resource: "@AppDollyBundle/Resources/config/shop_routing.yml"
    prefix:   /shop

# dummy profile pages
dolly_profile:
    resource: "@AppDollyBundle/Resources/config/profile_routing.yml"
    prefix: /min-side

dolly_restaurant_index:
    path:     /restauranter
    defaults: { _controller: AppDollyBundle:Restaurant:index }

dolly_restaurant_show:
    path:     /restauranter/{id}
    defaults: { _controller: AppDollyBundle:Restaurant:show }

dolly_test_product_page:
    path: /testproduct
    defaults: { _controller: AppDollyBundle:Dolly:productTest }

dolly_contact_form:
    path:     /kontakt-oss
    defaults: { _controller: AppDollyBundle:ContactForm:show }

dolly_menu_page:
    path: /meny/{id}
    defaults: { _controller: AppDollyBundle:Dolly:menu }

dolly_payment:
    path: /checkout/payment
    defaults: { _controller: AppDollyBundle:Payment:index }

dolly_confirmation:
    path: /checkout/confirmation
    defaults: { _controller: AppDollyBundle:Dolly:confirmation }

dolly_customize_page:
    path: /customize
    defaults: { _controller: AppDollyBundle:Dolly:customize }

dolly_cart:
    path: /checkout/cart
    defaults: { _controller: AppDollyBundle:Shop:cartIndex}

# following declaration should remain the LAST
dolly_contentpage:
    path: /{id}
    defaults: { _controller: AppDollyBundle:ContentPage:showBySlug }
    requirements:
        id: "^(?!login|logout|backoffice|elfinder|assets|efconnect|cart|api|css|rest|js|connect|ru|en|no|akuma|uploads).*$"