# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'WebBundle']
    java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: ['/usr/lib/node_modules','/usr/local/lib/node_modules']
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifyjs
            apply_to: "\.js$"
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifycss
    assets:
        jquery:
            inputs:
                  - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.3.js
            filters:
                - uglifyjs2
            output: js/jquery.min.js
        web_css:
            inputs:
                - bundles/web/styles/vendor.css
                - bundles/web/styles/main.css
                - bundles/web/styles/oblasti.css
            filters: [ uglifycss, cssrewrite ]
            output: css/web.min.css
        web_head_js:
            inputs:
                - @jquery
                - js/bootstrap.js
            filters: [ uglifyjs2 ]
            output: js/web-head.min.js
        web_footer_js:
            inputs:
                - bundles/web/js/app.js
            filters: [ uglifyjs2 ]
            output: js/web-footer.min.js
