# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'AppBackOfficeBundle', 'AppDollyBundle', 'FMElfinderBundle', 'AppApiBundle' ]
#    bundles:        [AppDollyBundle]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: ['/usr/lib/node_modules','/usr/local/lib/node_modules']
            apply_to: "\.less$"
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
    assets:
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

        jquery:
            inputs:
                  - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.3.js
            filters:
                - yui_js
            output: js/jquery.min.js

        # BackOffice
        bo_css:
            inputs:
                - css/bootstrap.css
                - assets/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
                - bundles/appbackoffice/css/nxc.css
            filters: [ yui_css, cssrewrite ]
            output: css/backoffice.min.css
        bo_head_js:
            inputs:
                - @jquery
                - js/bootstrap.js
            filters: [ yui_js ]
            output: js/backoffice-head.min.js
        bo_footer_js:
            inputs:
                - assets/moment/min/moment.min.js
                - assets/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            filters: [ yui_js ]
            output: js/backoffice-footer.min.js

        # Dolly
        dolly_css:
            inputs:
                - bundles/appdolly/styles/vendor.css
                - bundles/appdolly/styles/main.css
            filters: [ yui_css, cssrewrite ]
            output: css/dolly.min.css
        dolly_head_js:
            inputs:
                - @jquery
                - bundles/appdolly/js/modernizr.js
            filters: [ yui_js ]
            output: js/dolly-head.min.js
        dolly_footer_js:
            inputs:
                - bundles/appdolly/js/vendor.js
                - bundles/appdolly/js/app.js
            filters: [ yui_js ]
            output: js/dolly-footer.min.js
