imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: assetic.yml }
    - { resource: "@AppBackOfficeBundle/Resources/config/services.xml" }
    - { resource: "@AppCoreBundle/Resources/config/services.xml" }
    - { resource: "@AppDollyBundle/Resources/config/services.xml" }

framework:
    #esi:             ~
    translator: { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 43200
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdolifetime
    fragments:       ~
    http_method_override: true
    session: "%kernel.root_dir%/session/"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
            resources: ['bootstrap_3_layout.html.twig']
#    form:
#        resources:
#            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        schema_filter: ~^(?!t_)~
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
         auto_generate_proxy_classes: "%kernel.debug%"
         auto_mapping: true
         mappings:
#             translatable:
#                 type: annotation
#                 is_bundle: false
#                 alias: Gedmo
#                 prefix: Gedmo\Translatable\Entity
#                 dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: App\CoreBundle\Entity\User
    group:
        group_class: App\CoreBundle\Entity\Group

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


white_october_breadcrumbs:
    separator:          defaults to '/'
    separatorClass:     defaults to 'separator'
    listId:             defaults to 'wo-breadcrumbs'
    listClass:          defaults to 'breadcrumb'
    itemClass:          defaults to ''
    linkRel:            defaults to ''
    locale:             defaults to null, so the default locale is used
    translation_domain: defaults to null, so the default domain is used
    viewTemplate:       defaults to "WhiteOctoberBreadcrumbsBundle::breadcrumbs.html.twig"

app_dolly:
    contact_form:
        email:
            # Main recipient of the request form
            to: lars@norse.digital
            # Additional recipients of the request form
            # add email addresses in array
            bcc: []
            # The sender's email address
            # If this setting is not defined the sender will be the email address from 
            # the contact form. However sending emails from the webserver for domains
            # we don't control may cause issues with spam-detection on the recipients end.
            from: dolly@dolly.no

app_back_office:
    appearance:
        ckeditor:
            toolbar:
                - name: styles
                  items: ['Format', 'Font', 'FontSize']
                - name: colors
                  items: ['TextColor', 'BGColor']
                - name: tools
                  items: ['Maximize', 'ShowBlocks']
                - name: clipboard
                  items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - name: document
                  items: ['Source']
                - "/"
                - name: basicstyles
                  items: ['Bold', 'Italic', 'Underline', 'Strike']
                - name: paragraph
                  items: ['NumberedList', 'BulletedList', '-', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']
                - name: links
                  items: ['Link', 'Unlink', 'Anchor']
                - name: insert
                  items: ['Image', 'Table', 'Iframe', 'HorizontalRule', 'SpecialChar']

akuma_bootswatch:
    less_filter: less
    bootswatch:
        theme: "flatly"

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow:
                            - 'image/gif'
                            - 'image/jpeg'
                            - 'image/pjpeg'
                            - 'image/png'
                            - 'application/zip'
                            - 'application/x-java-archive'
                            - 'application/x-gzip'
                            - 'application/x-tar'
                            - 'application/x-rar-compressed'
                            - 'application/pdf'
                        upload_deny: ['all']
                        upload_max_size: 2M

ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }

fos_rest:
    routing_loader:
        default_format:       html
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: '^/css', priorities: [ 'css' ], fallback_format: false, prefer_extension: true }
            - { path: '^/js', priorities: [ 'js' ], fallback_format: false, prefer_extension: true }
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    disable_csrf_role: ROLE_API

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            Propel:
                namespace_prefix: ""
                path: "@AppCoreBundle/Resources/config/serializer"
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "@AppCoreBundle/Resources/config/serializer"

hwi_oauth:
    firewall_name: secured_area
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook.api.id%
            client_secret:       %facebook.api.secret%
            scope: "email"
            options:
                display: popup

services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix_except_default

a2lix_translation_form:
    locales: %locales%
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

