app_back_office_delivery_index:
    path:     /
    defaults: { _controller: AppBackOfficeBundle:DeliveryRoute:index }

app_back_office_delivery_update:
    path:     /{id}/update
    defaults: { _controller: AppBackOfficeBundle:DeliveryRoute:update }

app_back_office_delivery_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBackOfficeBundle:DeliveryRoute:delete }

app_back_office_delivery_restaurant:
    path:     /{id}
    defaults: { _controller: AppBackOfficeBundle:DeliveryRoute:show }
    requirements:
            id: \d+
