app_back_office_content_index:
    path:     /
    defaults: { _controller: AppBackOfficeBundle:ContentPage:index }

app_back_office_content_create:
    path:     /create
    defaults: { _controller: AppBackOfficeBundle:ContentPage:create }

app_back_office_content_show:
    path:     /{id}
    defaults: { _controller: AppBackOfficeBundle:ContentPage:show }

app_back_office_content_update:
    path:     /{id}/update
    defaults: { _controller: AppBackOfficeBundle:ContentPage:update }

app_back_office_content_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBackOfficeBundle:ContentPage:delete }

#app_back_office_content_test:
#    path:     /test
#    defaults: { _controller: AppBackOfficeBundle:ContentPage:test }
