app_back_office_up_sale_index:
    path:     /
    defaults: { _controller: AppBackOfficeBundle:UpSale:index }

app_back_office_up_sale_add_group:
    path:     /add_group
    defaults: { _controller: AppBackOfficeBundle:UpSale:AddGroup }

app_back_priority_product_index:
    path:     /product_priority/{id}
    defaults: { _controller: AppBackOfficeBundle:UpSale:productIndex }
    requirements:
        id: \d+

app_back_priority_group_delete:
    path:     /{id}
    defaults: { _controller: AppBackOfficeBundle:UpSale:removeGroup }
    requirements:
        id: \d+

app_back_priority_group_change:
    path:   /change_group
    defaults: { _controller: AppBackOfficeBundle:UpSale:changeGroup }

app_back_priority_products_change:
    path:   /change_product/{id}
    defaults: { _controller: AppBackOfficeBundle:UpSale:changeProduct }
    requirements:
        id: \d+

app_back_office_up_sale_add_product:
    path:   /add_product/{id}
    defaults: { _controller: AppBackOfficeBundle:UpSale:AddProduct }
    requirements:
        id: \d+

app_back_priority_product_delete:
    path:   /remove_product/{id}
    defaults: { _controller: AppBackOfficeBundle:UpSale:removeProduct }
    requirements:
        id: \d+