app_back_office_product_index:
    path:     /
    defaults: { _controller: AppBackOfficeBundle:Product:index }

app_back_office_product_show:
    path:     /{id}
    defaults: { _controller: AppBackOfficeBundle:Product:show }
    requirements:
        id: \d+
        
app_back_office_product_create:
    path:     /create
    defaults: { _controller: AppBackOfficeBundle:Product:create }

app_back_office_product_update:
    path:     /{id}/update
    defaults: { _controller: AppBackOfficeBundle:Product:update }
    requirements:
            id: \d+

app_back_office_product_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBackOfficeBundle:Product:delete }
    requirements:
            id: \d+

app_back_office_product_setting_edit:
    path:     /settings/{id}/update
    defaults: { _controller: AppBackOfficeBundle:Product:settingsUpdate }
    requirements:
            id: \d+

app_back_office_product_setting_delete:
    path:     /settings/{id}/delete
    defaults: { _controller: AppBackOfficeBundle:Product:settingsDelete }
    requirements:
            id: \d+

app_back_office_product_setting_create:
    path:     /settings/create
    defaults: { _controller: AppBackOfficeBundle:Product:settingsCreate }

app_back_office_product_setting_index:
    path:     /settings/index
    defaults: { _controller: AppBackOfficeBundle:Product:settingsList }

app_back_office_product_options_index:
    path:     /options/index
    defaults: { _controller: AppBackOfficeBundle:Product:optionsList }

app_back_office_product_options_edit:
    path:     /options/{id}/update
    defaults: { _controller: AppBackOfficeBundle:Product:optionsUpdate }
    requirements:
            id: \d+

app_back_office_product_options_delete:
    path:     /options/{id}/delete
    defaults: { _controller: AppBackOfficeBundle:Product:optionsDelete }
    requirements:
            id: \d+

app_back_office_product_options_create:
    path:     /options/create
    defaults: { _controller: AppBackOfficeBundle:Product:optionsCreate }
