web_rules:
    path:     /rules
    defaults: { _controller: WebBundle:Rules:index }

web_blog:
    path:     /blog
    defaults: { _controller: WebBundle:Blog:index }

web_city:
    path:     /region/city/{url}
    defaults: { _controller: WebBundle:Default:city }
    requirements:
        id: \w+

web_news:
    path:     /news/
    defaults: { _controller: WebBundle:Default:news }
    requirements:
        id: \d+

web_region:
    path:     /region/{url}
    defaults: { _controller: WebBundle:Default:region }
    requirements:
        id: \w+