more_role_page:
    resource: "@WebBundle/Resources/config/admin.yml"
    prefix:   /admin_panel

web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

web_photo:
    path:     /photo
    defaults: { _controller: WebBundle:Default:photo }

web_video:
    path:     /video
    defaults: { _controller: WebBundle:Default:video }

web_auto:
    path:     /auto/{id}
    defaults: { _controller: WebBundle:Default:auto }
    requirements:
        id: \d+